[tool.poetry]
name = "playwright-trial"
version = "0.1.0"
description = ""
authors = ["Arash"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
httpx = "^0.26.0"
playwright = "^1.41.2"
bs4 = "^0.0.2"
pandas = "^2.2.0"
matplotlib = "^3.8.3"
seaborn = "^0.13.2"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
